### ISSUE TITLE
Is it worth buying a Geared license?

### ISSUE THREAD

**Issue by TwoPintMatty** [Live-Charts/Live-Charts#913]
Has anyone else purchased the Geared package recently? I have emailed to try out the free Geared version but I do not feel comfortable buying the package as the project seems to have basically came to a halt.

I would like to try out the Community Edition but I have not received a response.

Is the community edition still available or is no-one receiving a response now?

**Comment by Vezill** [comment]
I'm trying to figure this out myself. While I'm pretty happy with the performance of Geared, if the project isn't going to continue I'll need to go looking for an alternative WinForms charting library (again) =\.

**Comment by TwoPintMatty** [comment]
I want to keep using Live Charts, and I love Geared when I tried it. However, I am a student and I just don't have the money to pay for the license at the moment so I have requested the community edition with no response to my emails which is unfortunate. 

I have been working on a project for a while now and it will be a lot of effort to port it to a different Chart application

**Comment by TwoPintMatty** [comment]
@beto-rodriguez @btordz could you help out please?

**Comment by beto-rodriguez** [comment]
The geared package has a 10 days trial, you can see a set of working samples at:

https://github.com/Live-Charts/GearedExamples

I wont stop maintaining the project, version 1 is really advanced with many new cool features. if you want to know more please take a look at:

https://github.com/Live-Charts/Live-Charts/issues/894

**Comment by TwoPintMatty** [comment]
Thank you for the response Beto, that's reassuring. Is the community version no longer given out? Would appreciate a response, thanks

**Comment by TwoPintMatty** [comment]
@beto-rodriguez The difference between the Community Edition and Geared WPF is private mail support, does this still apply? I am just looking for more information on the product before I decide to purchase or not. Thank you

**Comment by TwoPintMatty** [comment]
Hi @beto-rodriguez, I don't want to bother you but I will ask again as I don't want to pay approx ~£70 for Geared unless I know that the paid version gives the private mail support.

**Comment by TwoPintMatty** [comment]
@beto-rodriguez I have purchased the full version, hopefully the private mail support is still valid.

**Comment by istvanns** [comment]
I requested my company to buy the Geared license, because the free version is unusable if you have a lot of data and need high performance. The performance of Geared is amazing, especially for the price. I really hope that it's not dead, it would be very unfortunate for those who bought it or intend to buy it. A similar library, like SciChart, costs 10 times more. I think there's a great need and a lot of demand for Geared. If companies have the choice between paying 100 or 1000 or more USD for such a feature-rich and high-performance library, they will pick the cheaper option, **given that it's properly supported and actively developed**. It would be very sad if this project was just left behind to die like this.
