### ISSUE TITLE
Geared Support

### ISSUE THREAD

**Issue by lefig** [Live-Charts/Live-Charts#993]
Now what I find rather strange concerning Geared is that there is apparently no support. 

Despite me having sent several email requests concerning single developer usage I have never received a reply. 

Although rather impolite I put the failure to reply as down to simply poor customer service.

But I have drawn a conclusion that there is indeed no support in existence for Geared.

I would suggest that you remove all references to avoid potentially frustrated applicants.

**Comment by mirthestam** [comment]
Maybe the developer is interested in open-sourcing the geared source.

**Comment by lefig** [comment]
Now that is a very pleasant thought. It would certainly help make development of the excellent Lean Monitor project easier.

**Comment by recounter7** [comment]
It would be really nice to have any kind of reaction from @beto-rodriguez. 
Latest activity was in January i think.
So please @beto-rodriguez are you still out there?
Here are so many people who love LiveCharts and also would love to buy LiveCharts Geared to support your great work. But it seems that the project is dead.

**Comment by lefig** [comment]
Hi @recounter7, thank you for making this request on behalf of all users. There are likely to be many other users that use both libraries with and with respective project dependencies. They need to know this before committing more investment of their time and energy into using this work.

**Comment by fabolo** [comment]
I'm in the process of evaluating Geared, already spent considerable amount of time developing an app with charts using SpecializedElements, 'I join the request for a sign from @beto-rodriguez

**Comment by lefig** [comment]
Well, there appears to be a consensus that users would appreciate knowing either way whether to discontinue using code with dependency on either Geared or LC. I for one am looking at another popular .net chart project simply to avoid potential frustration and lost time effort.

**Comment by beto-rodriguez** [comment]
I am sorry for not answering your free license request mails, this license will dropped in a near future, I will try to explain why:

@lefig @recounter7  @fabolo There is support in the Geared package, The library consumes a lot of time to develop and to support the users, I try to help as much as I can and I read every mail at support@lvcharts.net.

We now do not answer the free license request we get. That license will be dropped in the near future. We already provide a free version of the library, a lot of samples and documentation, @lefig  when we as developers use an open source project, we should also try to help the library and the community, could please get more involved in the documentation, you would help the library a lot by not making this negative comments about the library, as you might understand this project started as for a project of my own, and I decided to share it with the community, it has been a really long and challenging process.

I hope the library fits your needs, and helps you to build many applications, I will close this issue for now, I don't see the point in it.

**Comment by Mrxx99** [comment]
@beto-rodriguez this questions only were raised because the project seemed dead to them. Some people apparently got no or late support (just what I heard) over mail despite using geared and the overall state of the project was unclear. So it's not that users don't want to pay but users worried that geared funcionality is lost, if you had dropped the project.

That aside I want to thank you for that great library I really love it and hope it won't die. I am planning to also try geared to support this.

Seems you currently don't have much time for the project, maybe moving it to the .net foundation would attract more contributors.

And by the way one indicator that makes the project look dead is the ETA on the readme for 1.0 of September *2018*.

**Comment by istvanns** [comment]
I'd like spread the word about how fantastic LiveCharts, especially the Geared package is, through sharing my personal experience with it:

I use LiveCharts to develop a WPF app, where line charts display live DateTimePoint data. Using the normal charts is all right, if you don't need to display a lot of data. In my case, when the chart had about 1000 points, CPU usage climbed up to about 40% and stayed there persistently. After about 2000 points, the UI just stopped updating. This was with animations turned off, hovering and tooltips disabled. I had to set PointGeometry to null, which completely solved the performance problem, but now I only had lines, without points. This was not cool, since zooming in and being able to see each point was important.
Then, I installed the Geared package to start the trial period and see how it works. Using Geared, I had no performance problems any more! Even with 5000 points, with low quality, hovering and tooltips enabled and animations disabled, the charts are extremely fast, light, and consume only about 1% CPU! So I immediately requested my company to buy a single developer license for me!

LiveCharts Geared is INCREDIBLY FAST AND LIGHTWEIGHT and it ONLY costs 99 USD per developer, which is a perpetual license! It's RIDICULOUS! Similar solutions, like SciChart cost 10 times more and need to be renewed yearly! The free LiveCharts is fantastic, if you have small data sets to display, like a few dozens or maybe up to a few hundred, I'd say. But if you have a lot of data and need performance, LiveCharts Geared for 99 USD is ABSOLUTELY AMAZING and UNBEATABLE! I'm talking from personal experience here!

So I'd like to encourage everybody to buy the Geared license and support this fantastic project, and/or contribute any way you can! **Having such a performant, feature-rich, easy-to-use charting library for such a low price is not to be taken for granted.** If LiveCharts and Geared stops being actively developed, what other options do we have left? If you need nice looking, feature-rich, fast and lightweight charts with zooming, panning, tooltips, MVVM support and a lot of other useful stuff, it's either Geared for 99 USD or SciChart or something similar for 1000 USD and above, with yearly license renewals. I know there are some other charting solutions as well, but I don't know anything else that offers what LiveCharts has to offer, especially for that price! As a developer, working for a company making real business, I have this to say to Beto and fellow devs:

BETO, PLEASE CONTINUE DEVELOPMENT, LIVECHARTS IS BADLY NEEDED!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
DEVELOPERS, PLEASE SUPPORT THIS FANTASTIC PROJECT BY BUYING THE GEARED LICENSE!!!!!!

Please keep it up Beto!!!
